-- La siembra de datos se movio a un seeder en Java: com.minimarket.config.DataSeeder
-- Ahi las contraseñas vienen del .env y se hashean con BCrypt en tiempo de ejecucion,
-- en vez de pegar un hash quemado en este archivo.
-- Este SQL queda intencionalmente vacio (y spring.sql.init.mode=never lo deshabilita).
